/**
 * IDL description of the ClusterModule
 *
 * This file is automatically parsed by the rurbuilder backends for the omniidl 
 * compiler. The names of the functions will become port identifiers. The names 
 * of the function variables are not used. For now, if the function variable 
 * ends with a number, like "void Sensor(in long input2);" there will be two
 * portnames created.
 */

#pragma author You
#pragma copyright Your Company
#pragma date 21 Jun. 2013
#pragma license LGPLv3

// Recommended namespace "rur"
module rur {

// The command-line parameter (this struct is required)
struct Param {
  // multiple modules can be addressed in parallel, killed, etc. using "module_id"
  string module_id;
  // a certain parameter over the command-line (long becomes int) 
  long parameter;
};

// Typedef for array of integers
typedef sequence<long> long_seq;

// The public interface of ClusterModule
interface ClusterModule {

  // Input from microphone in the form of an array
  void Audio(in long_seq input);

  // Input from infrared sensor
  void Infrared(in long sensor_l);

  // A command to one of the wheels
  void LeftWheel(out long output);

};

};
